// Collects every open [confirm] item into docs/confirm-report.md for Rae (plan §5, Phase 2 acceptance):
// dealership.json, fees.json, claims.json, testimonials.json, each unit's confirm list, and every
// <Confirm note="…"> in the source. `--strict` exits 1 while anything is open (use before launch).
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';

const json = (p) => JSON.parse(readFileSync(p, 'utf8'));
const dealership = json('src/data/dealership.json');
const fees = json('src/data/fees.json');
const claims = json('src/data/claims.json');
const testimonials = json('src/data/testimonials.json');
const inventory = json('src/data/inventory.json');

// <Confirm note="…" /> and <Confirm note={'…'} /> in components and pages, with the file they're in.
const notes = new Map();
const walk = (dir) => {
  for (const f of readdirSync(dir)) {
    const p = join(dir, f);
    if (statSync(p).isDirectory()) { walk(p); continue; }
    if (!/\.(astro|tsx)$/.test(p)) continue;
    for (const m of readFileSync(p, 'utf8').matchAll(/<Confirm note=(?:"([^"]+)"|\{['"]([^'"]+)['"]\})/g)) {
      const note = m[1] ?? m[2];
      if (!notes.has(note)) notes.set(note, new Set());
      notes.get(note).add(p.replaceAll('\\', '/').replace(/^src\//, ''));
    }
  }
};
walk('src');

const lines = [
  '# Open [confirm] items',
  '',
  `Generated by \`npm run confirm-report\` on ${new Date().toISOString().slice(0, 10)}. Everything here is shown on the review build with a yellow [confirm] chip and needs an answer from Rae (or Paul) before launch.`,
  '',
  '## Business details (`src/data/dealership.json`)',
  ...dealership.confirm.map((c) => `- [ ] ${c}`),
  '',
  '## Fees (`src/data/fees.json`)',
  ...fees.confirm.map((c) => `- [ ] ${c}`),
  '',
  '## Claims from the old site (`src/data/claims.json`, hidden in production until confirmed)',
  ...claims.items.filter((c) => !c.confirmed).map((c) => `- [ ] ${c.text}`),
  '',
  '## Testimonials (`src/data/testimonials.json`)',
  ...(testimonials.confirmed ? [] : [`- [ ] ${testimonials.confirm}`]),
  '',
  '## Units (`src/data/inventory.json`)',
];
let unitItems = 0;
for (const u of inventory) {
  if (!u.confirm?.length) continue;
  lines.push(`### ${u.year} ${u.make}${u.series ? ` ${u.series}` : ''} ${u.model} (${u.stockNumber})`);
  for (const c of u.confirm) { lines.push(`- [ ] ${c}`); unitItems++; }
  lines.push('');
}
lines.push('## Flags in page copy', '');
for (const [note, files] of [...notes].sort()) lines.push(`- [ ] ${note} (${[...files].join(', ')})`);
lines.push('');

const total = dealership.confirm.length + fees.confirm.length + claims.items.filter((c) => !c.confirmed).length + (testimonials.confirmed ? 0 : 1) + unitItems + notes.size;
writeFileSync('docs/confirm-report.md', lines.join('\n'));
console.log(`docs/confirm-report.md: ${total} open item(s)`);
if (process.argv.includes('--strict') && total > 0) process.exit(1);
